### ISSUE TITLE
Modify “Summary” title in Site Assessment Property Info

### ISSUE THREAD

**Issue by dandahle** [dandahle/Catalyst-AppVetting#41] opened 2018-01-03 04:29 UTC
Modify “Summary” title in Site Assessment Property Info to show / add instructions that it is for any site assessment notes other than Work Items for Vetting Agent

**Comment by ironmikesh** [comment] 2018-01-03 04:32
Duplicate of !40

**Closed by ironmikesh** 2018-01-03 04:32 UTC
